language: node_js
node_js:
 - "0.10"
sudo: false

before_install:
 - npm install -g grunt-cli bower
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - bower install

script: grunt clean default

after_script:
 - grunt coveralls
